### ISSUE TITLE
[Enhancement] Namespace health check pending pods - issue text and next steps

### ISSUE THREAD

**Issue by more-dinner** [runwhen-contrib/rw-cli-codecollection#197]
**Observation** 
![Screen Shot 2023-08-31 at 11 23 37 PM](https://github.com/runwhen-contrib/rw-cli-codecollection/assets/10690011/c846463b-6a6e-4f8d-86e9-45610fc1e0e2)

1) The issue string "Pending Pods Found In Namespace online-boutique and 11 more", specifically the "and 11 more" seems a bit confusing.  11 more what?

2)  I can't seem to find 11 of anything in the details.  I see 4 references to what I think is the same pod, and it doesn't look unhealthy...  (details below)

3) The expected "pods should not be stuck pending" has an insight that is not clear in the details - are these pods stuck in a pending state, or are they in this state just for a few seconds while this command was running and this may resolve itself?

4) Less of an issue, but I noticed that report is extremely large, likely because of this:
```
Commands Used:
kubectl get all --context sandbox-cluster-1 -n online-boutique -o json
```

```
Pods pending with reasons:
"---
pod_name: adservice-795589cf6f-dqnts
status: Pending
message: containers with unready status: [server]
reason: ContainersNotReady
containerStatus: {"waiting":{"reason":"ContainerCreating"}}
containerMessage: N/A
containerReason: ContainerCreating
---

---
pod_name: adservice-795589cf6f-dqnts
status: Pending
message: containers with unready status: [server]
reason: ContainersNotReady
containerStatus: {"waiting":{"reason":"ContainerCreating"}}
containerMessage: N/A
containerReason: ContainerCreating
---

---
pod_name: adservice-795589cf6f-dqnts
status: Pending
message: containers with unready status: [server]
reason: ContainersNotReady
containerStatus: {"waiting":{"reason":"ContainerCreating"}}
containerMessage: N/A
containerReason: ContainerCreating
---

---
pod_name: adservice-795589cf6f-dqnts
status: Pending
message: containers with unready status: [server]
reason: ContainersNotReady
containerStatus: {"waiting":{"reason":"ContainerCreating"}}
containerMessage: N/A
containerReason: ContainerCreating
---
```

**Current Outcome** 

**Desired Outcome**

**Comment by jon-funk** [comment]
1. Touches on the problems-to-issues we chatted about this morning. That would be "11 more problems" of similar nature in the same parse but only the first occurence is used in the details. There's a few options for this one, depending on complexity/accuracy desired. I could just tack on the "problems" part and update the details string to include all. Other options involve multiple issue submissions, having a problem list as part of an issue submission, etc.

2. I'll look at why there's duplication

3. I see this as being tackled by nextsteps, as we'll need to perform more investigation with other tasks to determine what kind of problem the pod is experiencing based on it's pending status

4. Do you mean the file size? I'm guessing that's https://github.com/runwhen-contrib/rw-cli-codecollection/blob/main/codebundles/k8s-namespace-healthcheck/runbook.robot#L174 which might be a bit tricky to replace, since as part of the condition check we do need to pull resources to determine their status condition, so removing those types from the fetch means you potentially miss an issue

**Comment by jon-funk** [comment]
Closing - outdated after nextsteps rework - calling add issue keyword directly
